# -*- coding: utf-8 -*-
"""Video Analyzer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HtFbIYlNApSt8H6kZcTofyNoOnHUAa0s
"""

!pip install ultralytics --quiet

import cv2
import numpy as np
import matplotlib.pyplot as plt
import time
import os
import torch
from ultralytics import YOLO

from google.colab import drive
drive.mount('/content/drive')

VIDEO_PATH = "/content/drive/MyDrive/CPS843 Project/DATA1.mp4"

print("Video exists:", os.path.exists(VIDEO_PATH))

# YOLOv5n via torch hub
model_5n = torch.hub.load("ultralytics/yolov5", "yolov5n", pretrained=True)

# YOLOv8n via ultralytics
model_8n = YOLO("yolov8n.pt")

print("Models loaded successfully.")

FRAME_SKIP = 1

VEHICLE_CLASSES = ["car", "truck", "bus", "motorbike"]

def run_model(model, label):
    cap = cv2.VideoCapture(VIDEO_PATH)

    frame_counts = []
    total_count = 0
    frame_index = 0
    start_t = time.time()

    while True:
        ret, frame = cap.read()
        if not ret:
            break

        # skip frames
        if frame_index % FRAME_SKIP != 0:
            frame_index += 1
            continue

        try:
            # YOLOv8 model call
            results = model(frame, conf=0.25, iou=0.5)[0]
            boxes = results.boxes
            v5 = False
        except Exception:
            # YOLOv5 model call
            results = model(frame)
            boxes = results.pred[0]
            v5 = True

        count = 0

        # YOLOv8 format
        if not v5:
            for box in boxes:
                cls_id = int(box.cls[0])
                if model.names[cls_id] in VEHICLE_CLASSES:
                    count += 1

        # YOLOv5 format
        else:
            for *xyxy, conf, cls in boxes:
                cls_id = int(cls)
                if model.names[cls_id] in VEHICLE_CLASSES:
                    count += 1

        frame_counts.append(count)
        total_count += count
        frame_index += 1

    cap.release()

    fps = frame_index / (time.time() - start_t)

    return {
    "label": label,
    "per_frame": frame_counts,
    "total": total_count,
    "fps": fps,
    "frames": frame_index,
    "processing_time": time.time() - start_t
}

res_5n = run_model(model_5n, "YOLOv5n")
res_8n = run_model(model_8n, "YOLOv8n")

print("Processing complete.")

print(f"Total Frames Processed: {res_5n['frames']}")

print("\nFPS")
print(f"YOLOv5n FPS: {res_5n['fps']:.2f}")
print(f"YOLOv8n FPS: {res_8n['fps']:.2f}")

print("\nTotal Vehicle Detections")
print(f"YOLOv5n Total: {res_5n['total']}")
print(f"YOLOv8n Total: {res_8n['total']}")

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import matplotlib.pyplot as plt

plt.figure(figsize=(14,6))
plt.plot(res_5n["per_frame"], label="YOLOv5n", linewidth=1)
plt.plot(res_8n["per_frame"], label="YOLOv8n", linewidth=1)
plt.title("PerFrame Vehicle Count Comparison")
plt.xlabel("Frame")
plt.ylabel("Vehicles Detected")
plt.grid(True)
plt.legend()
plt.show()

plt.figure(figsize=(6,4))
plt.bar(["YOLOv5n", "YOLOv8n"],
        [res_5n["fps"], res_8n["fps"]],
        color=["blue","orange"])
plt.title("FPS Comparison")
plt.ylabel("Frames per Second")
plt.show()

plt.figure(figsize=(6,4))
plt.bar(["YOLOv5n", "YOLOv8n"],
        [res_5n["total"], res_8n["total"]],
        color=["green","red"])
plt.title("Total Vehicle Detections")
plt.ylabel("Total Count")
plt.show()

# Extract processing times
time_5n = res_5n["processing_time"]
time_8n = res_8n["processing_time"]

# Compute average time per processed frame
avg_5n = time_5n / res_5n["frames"]
avg_8n = time_8n / res_8n["frames"]

print("Processing Time Summary")
print(f"YOLOv5n Total Time: {time_5n:.2f} seconds")
print(f"YOLOv8n Total Time: {time_8n:.2f} seconds")
print()
print(f"YOLOv5n Avg Time per Frame: {avg_5n:.4f} s")
print(f"YOLOv8n Avg Time per Frame: {avg_8n:.4f} s")

# Bar chart of processing times
plt.figure(figsize=(7,5))
plt.bar(["YOLOv5n", "YOLOv8n"],
        [time_5n, time_8n],
        color=["purple", "cyan"])

plt.title("Total Processing Time Comparison")
plt.ylabel("Time (seconds)")
plt.grid(axis="y", linestyle="--", alpha=0.6)
plt.show()

# Bar chart of average time per frame
plt.figure(figsize=(7,5))
plt.bar(["YOLOv5n", "YOLOv8n"],
        [avg_5n, avg_8n],
        color=["green", "orange"])

plt.title("Average Processing Time Per Frame")
plt.ylabel("Seconds per Frame")
plt.grid(axis="y", linestyle="--", alpha=0.6)
plt.show()